eureka:
  instance:
    hostname: localhost
  client:  # Not a client, don't register with yourself (unless running
    # multiple discovery servers for redundancy)
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 8083   # HTTP (Tomcat) port