spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zafin
    username: micorprt
    password: micorprt
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: accounts-service


# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

